task: ["MLM"]
batch_size: [8, 16, 32]
dropout: [0.0, 0.1, 0.4]
epochs: [50, 100, 150, 200, 300]
hidden_channels: [32, 64, 128]
lr: [0.001, 0.0001]
num_layers: [2, 3, 4]
seed: [42]
split_method: ["stratified", "scaffold", "sts"]
